CREATE TABLE [dbo].[Usuario] (
	[Id] INT NOT NULL IDENTITY,
	[Nome] VARCHAR (50) NOT NULL,
	[Login] VARCHAR (15) NOT NULL,
	[Senha] VARCHAR (150) NOT NULL,
	[Email] VARCHAR (150) NOT NULL,
	[DataCriacao] DATETIME NOT NULL,
	PRIMARY KEY CLUSTERED ([Id] ASC)
);